apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "inspect-pod-nodejs.fullname" . }}
  labels:
    app: {{ include "inspect-pod-nodejs.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ include "inspect-pod-nodejs.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "inspect-pod-nodejs.name" . }}
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
          env:
            {{- toYaml .Values.env | nindent 12 }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}

