replicaCount: 1

image:
  repository: asantar0/redjar-test-app
  tag: b9a19bd
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: dev.inspect-pod-nodejs.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}

imagePullSecrets:
  - name: regcred

podAnnotations:
  force-sync: "2025-07-16-18-00"

env:
  - name: POD_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
  - name: POD_NAMESPACE
    valueFrom:
      fieldRef:
        fieldPath: metadata.namespace
  - name: POD_IP
    valueFrom:
      fieldRef:
        fieldPath: status.podIP
  - name: NODE_NAME
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName

